[package]
name = "frost-taproot"
edition = "2021"
# When releasing to crates.io:
# - Update html_root_url
# - Update CHANGELOG.md
# - Create git tag.
version.workspace = true
authors = [
    "Deirdre Connolly <durumcrustulum@gmail.com>",
    "Chelsea Komlo <me@chelseakomlo.com>",
    "Conrado Gouvea <conradoplg@gmail.com>"
]
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = ["cryptography"]
keywords = ["cryptography", "crypto", "ed25519", "threshold", "signature"]
description = "A Schnorr signature scheme over secp256k1 that supports FROST."

[package.metadata.docs.rs]
features = ["serde"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
parity-scale-codec = { workspace = true }
k256 = { workspace = true, default-features = false, features = ["arithmetic", "schnorr", "expose-field", "hash2curve", "alloc"] }
frost-core = { workspace = true }
rand_core = { workspace = true, optional = true }
sha2 = { workspace = true }
signature = { workspace = true }
subtle = { workspace = true }

[features]
default = ["std"]
std = [
    "frost-core/std",
    "parity-scale-codec/std",
    "rand_core/std",
    "k256/std",
    "sha2/std",
]
